config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users
  resources :posts
  resources :orders do
    member do
      get 'user'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchandise.rb
class Merchandise < ApplicationRecord
    with_options presence: true do
        validates :merchandise_name
        validates :price
    end
    belongs_to :user
    
end

app/models/order.rb
class Order < ApplicationRecord
    with_options presence: true do
        validates :user
        validates :merchandise
        validates :mumber_of_orders
        validates :price
    end
    belongs_to :user
    belongs_to :merchandise
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :facility_name, presence: true

  has_many :merchandises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
      private
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:facility_name])
      end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @users = User.all
    end

    def user
        @user = User.find(params[:id])
    end

    def show
        @merchandise = Merchandise.find(params[:id])
        if  @merchandise.deadline != nil
            @year = @merchandise.deadline.year
            @month = @merchandise.deadline.month
            @day = @merchandise.deadline.day
        end
    end

    def new
        @merchandise = Merchandise.find(params[:format])
        @order = Order.new
    end

    def create
        @order = Order.new(order_params)
        if @order.save
            redirect_to root_path
        else
            render :new
        end
    end

    private

    def order_params
        params.require(:order).permit(:mumber_of_orders, :price, :merchandise_id).merge(user_id: current_user.id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        if user_signed_in?
            @merchandise = Merchandise.all
            @order = Order.where(user: current_user.id)
        end
    end

    def new
        @merchandise = Merchandise.new
    end

    def create
        @merchandise = Merchandise.new(merchandise_params)
        if @merchandise.save
            redirect_to root_path
        else
            render :new
        end
    end    

    def show
        @merchandise = Merchandise.find(params[:id])
    end

    def edit
        @merchandise = Merchandise.find(params[:id])
    end

    def update
        @merchandise = Merchandise.find(params[:id])
        if @merchandise.update(merchandise_params)
            redirect_to root_path
          else
            render :edit
          end
    end

    private

    def merchandise_params
        params.require(:merchandise).permit(:merchandise_name, :explanation, :price, :limit, :quantity, :deadline).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Order Reception</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    
  </header>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>商品の選択</h1>
    <% @users.each do |user| %>
        <div class="user">
            <%= link_to user_order_path(user.id) do %>
                <%= user.facility_name %>
            <% end %>
        </div>
    <% end %>
<div id="top-btn">
    <%= link_to "トップページ", root_path %>
</div>

app/views/orders/new.html.erb
<%= link_to "商品の選択", orders_path %> > <%= link_to @merchandise.user.facility_name, user_order_path(@merchandise.user.id) %> > <%= link_to @merchandise.merchandise_name ,order_path(@merchandise.id)  %> > 商品注文
<div>
    <h2><%= @merchandise.merchandise_name %></h2>
    <div>
        <% if @merchandise.limit == true %>
            数量限定商品 
            <%= @merchandise.quantity %> 個
        <% else %>
            注文上限なし
        <% end %>
    </div>
    <div>
        単価
        <em id="price">
            <%= @merchandise.price %>
        </em>
        円
    </div>
    <div>
        <%= @merchandise.explanation %>
    </div>
    <div>
        注文期限
    </div>
    <div>
        <% if @merchandise.deadline != nil %>
            <%= @merchandise.deadline.year %>年
            <%= @merchandise.deadline.month %>月
            <%= @merchandise.deadline.day %>日
        <% end %>
    </div>
</div>

<%= form_with model:@order, :url => {:action => :create} do |f| %>
    <ul>
        <li class="field">
            <%= f.label :注文数 %>
        </li>
        <li class="field">
            <%= f.number_field :mumber_of_orders ,id: "item-num" , min: 1, max: 1000 %>個(1~1000)
        </li>
        合計金額
        <li id="total-field">
            <%= f.number_field :price ,id: "orders-price-column"  %>円
        </li>
        <li class="field">
            <%= f.submit "購入予約" %>
        </li>
        <li>
            <%= f.number_field :merchandise_id ,value: @merchandise.id %>
        </li>
    </ul>
<% end %>

app/views/orders/show.html.erb
<%= link_to "商品の選択", orders_path %> > <%= link_to @merchandise.user.facility_name, user_order_path(@merchandise.user.id) %> > <%= @merchandise.merchandise_name %>
<div>
    <h2><%= @merchandise.merchandise_name %></h2>
    <div>
        <% if @merchandise.limit == true %>
            数量限定商品 
            <%= @merchandise.quantity %> 個
        <% else %>
            注文上限なし
        <% end %>
    </div>
    <div>
        単価<%= @merchandise.price %>円
    </div>
    <div>
        <%= @merchandise.explanation %>
    </div>
    <div>
        注文期限
    </div>
    <div>
        <% if @merchandise.deadline != nil %>
            <%= @year %>年
            <%= @month %>月
            <%= @day %>日
        <% end %>
    </div>
</div>

<div>
    <% if @merchandise.deadline != nil %>
        <% if @merchandise.deadline < Time.now %>
            <div id="limit-info">
                注文期限を過ぎています
            </div>
        <% else %>
            <%= link_to "注文する", new_order_path(@merchandise.id) %>
        <% end %>
    <% else %>
        <%= link_to "注文する", new_order_path(@merchandise.id) %>
    <% end %>
</div>

app/views/orders/user.html.erb
<%= link_to "商品の選択", orders_path %> > <%= @user.facility_name %>
<h1><%= @user.facility_name %></h1>

<div id="user-mer-info">
    出品中の商品一覧
</div>
<% @user.merchandises.each do |mer| %>
    <%= link_to order_path(mer.id) do %>
        <div class="user-mer-block">
            <div class="user-mer">
                <%= mer.merchandise_name %>
            </div>
            <div class="user-mer">
                <%= mer.price %>
            </div>
            <div class="user-mer">
                <%= mer.limit %>
            </div>
            <div class="user-mer">
                <%= mer.quantity %>
            </div>
            <div class="user-mer">
                <%= mer.deadline %>
            </div>
        </div>
    <% end %>
<% end %>
<div>
    <%= link_to "もどる", orders_path %>

app/views/posts/edit.html.erb
<h1>商品情報編集</h1>
<%= form_with model:@merchandise, :url => {:action => :update} do |f| %>

    <div>
        <ul>
            <li class="field">
                <%= f.label :商品名 %>
            </li>
            <li class="field">
                <%= f.text_field :merchandise_name %>
            </li>
            <li class="field">
                <%= f.label :詳細情報 %>
            </li>
            <li class="field">
                <%= f.text_area :explanation %>
            </li>
            <li class="field">
                <%= f.label :価格 %>
            </li>
            <li class="field">
                ￥<%= f.number_field :price %>
            </li>
            <li class="field">
                <%= f.label :数量限定 %>
                <%= f.check_box :limit %>
            </li>
            <li class="field">
                <%= f.label :数量 %>
            </li>
            <li class="field">
                <%= f.number_field :quantity %>
            </li>
            </li>
            <li class="field">
                <%= f.label :注文締め切り日 %>
            </li>
            <li class="field">
                <%= f.date_field :deadline %>
            </li>
            <li>
                <%= f.submit "登録する" %>
            </li>
        </ul>
    </div>
<% end %>

<%= link_to "トップページ" , root_path %>

app/views/posts/index.html.erb
<div class="app-title-card">
    <div class="app-title">Order Reception</div>
    <div class="app-title-ja">オーダー管理システム</div>
</div>

<div class="info-card">
    <% if user_signed_in? %>
        <div class="user-name">
            <%= current_user.facility_name %>
        </div>
        <div class="sign-in-info">
            として サインイン中です。
        </div>
        <div class="action">
            <div class="merchandise">
                <%= link_to "商品登録",  new_post_path %>
            </div>
            <div class="merchandise order">
                <%= link_to "注文",  orders_path %>
            </div>
            <div class="logout">
                <%= link_to 'ログアウト',  destroy_user_session_path, method: :delete %>
             </div>
        </div>
        <div class="mer-list-title">
            現在出品中の商品一覧
        </div>
        <table class="mer">
            <tr>
                <th>
                </th>
                <th class="mer-column">
                    商品名
                </th>
                <th class="mer-column">
                    商品単価
                </th>
                <th class="mer-column">
                    注文期限
                </th>
                <th class="mer-column">
                    商品数
                </th>
                <th class="mer-column">
                    注文締め切り日
                </th>
                <th>
                </th>
            </tr>
            <% @merchandise.each do |mer| %>
                <% if mer.user_id == current_user.id %>
                    <tr class="mer-value-box">
                        <td>
                            <div class="mer-value show">
                                <%= link_to "詳細" ,post_path(mer.id) %>
                            </div>
                        </td>
                        <td class="mer-value">
                            <%= mer.merchandise_name %>
                        </td>
                        <td class="mer-value">
                            <%= mer.price %>
                        </td>
                        <td class="mer-value">
                            <% if mer.limit == true %>
                                有
                            <% else %>
                                無
                            <% end %>
                        </td>
                        <td class="mer-value">
                            <%= mer.quantity %>
                        </td>
                        <td class="mer-value">
                            <%= mer.deadline %>
                        </td>
                        <td class="mer-value edit">
                            <%= link_to "編集" ,edit_post_path(mer.id) %>
                        </td>
                    </tr>
                <% end %>
            <% end %>
        </table>
        <% if @order.none? %>
            <div id="order-card">
                現在注文中の商品はありません
            </div>
        <% else %>
            <div id="order-card">
                現在注文中の商品
            </div>
        <% end %>
        <% @order.each do |order| %>
            <div>
                <%= order.merchandise.merchandise_name %>
                <%= order.mumber_of_orders %>個
                <%= order.price %>円
            </div>
        <% end %>
    <% else %>
        <div class="action">
            <div class="merchandise">
                <%= link_to "事業所登録" , new_user_registration_path %>
            </div>
            <div class="merchandise order">
                <%= link_to "ログイン",  new_user_session_path %>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>新規投稿画面</h1>
<%= form_with model:@merchandise, :url => {:action => :create} do |f| %>

    <div>
        <ul>
            <li class="field">
                <%= f.label :商品名 %>
            </li>
            <li class="field">
                <%= f.text_field :merchandise_name %>
            </li>
            <li class="field">
                <%= f.label :詳細情報 %>
            </li>
            <li class="field">
                <%= f.text_area :explanation %>
            </li>
            <li class="field">
                <%= f.label :価格 %>
            </li>
            <li class="field">
                ￥<%= f.number_field :price %>
            </li>
            <li class="field">
                <%= f.label :数量限定 %>
                <%= f.check_box :limit %>
            </li>
            <li class="field">
                <%= f.label :数量 %>
            </li>
            <li class="field">
                <%= f.number_field :quantity %>
            </li>
            </li>
            <li class="field">
                <%= f.label :注文締め切り日 %>
            </li>
            <li class="field">
                <%= f.date_field :deadline %>
            </li>
            <li>
                <%= f.submit "登録する" %>
            </li>
        </ul>
    </div>
<% end %>

<%= link_to "トップページ" , root_path %>

app/views/posts/show.html.erb
<h1>商品詳細</h1>

<div>
    <div id="show-name">
        <%= @merchandise.merchandise_name %>
    </div>
    <div id="show-exp">
        <%= @merchandise.explanation %>
    </div>
    <div id="show-price">
        <%= @merchandise.price %>
    </div>
    <div id="show-limit">
        <%= @merchandise.limit %>
    </div>
    <div id="show-qua">
        <%= @merchandise.quantity %>
    </div>
    <div id="show-dead">
        <%= @merchandise.deadline %>
    </div>
</div>
<%= link_to "編集" ,edit_post_path(@merchandise.id) %>
<%= link_to "もどる", root_path %>